signature_name: EntityAttributeExtraction 

# 运行时过滤：只保留公司/组织/人物
entity_type_whitelist: ["公司", "组织", "人物"]
disallow_entity_types: ["其他"]
default_entity_type: "公司"

descriptions:
  entity_list: "仅包含涉及的公司、组织或关键人物（如 娃哈哈集团、宗馥莉、宗庆后）"
  context: "输入原文上下文（新闻段落或滑动窗口）"
  entity_attributes: "{'name': 实体名, 'attributes': [固有属性 或 最新官方状态 ...]}"

prompt_blocks:
  - |
    任务目标：
    ▍仅针对【公司 / 组织 / 人物】抽取：
       ① 固有属性（稳定、不随时间变化）
       ② 最新官方状态（带日期或官方措辞）
    ▍若语句含“可能 / 或许 / 预计 / 计划于(无日期)” → 标注为推测，但仍保留。
    ▍如上下文涉及多个实体 → 分别独立输出。
  - |
    ──────────────────────────────
    ▍ 固有属性（举例）
      • 公司股东结构 / 持股比例 → “宗馥莉持股 29.4%”
      • 法人 / 董事长 / 总经理 → “法定代表人：宗馥莉”
      • 注册地 / 隶属关系     → “隶属杭州娃哈哈集团有限公司”
      • 家族关系 / 角色身份   → “宗馥莉：宗庆后之女”
  - |
    ▍ 最新官方状态（举例 — 必须带时间或官方措辞）
      • 股权变动        → “2024-08 已完成工商变更，宗馥莉继承 29.4% 股权”
      • 职务变动        → “2024-08 接任董事长兼总经理”
      • 诉讼进展        → “2025-06-13 庭前谈话已召开”
      • 官方回应        → “[娃哈哈法务 2025-08-27] 否认原告诉求有法律依据”
      • 政府/法院动作   → “上城区法院 2025-04 才送达立案材料”
  - |
    ──────────────────────────────
    输出示例：
    [
      {
        "name": "娃哈哈集团",
        "attributes": [
          "股东构成：宗馥莉 29.4%，上城区文商旅 46%，职工持股会 24.6%",
          "[2024-08] 宗庆后去世后，股权完成工商变更",
          "[2025-06-13] 庭前谈话召开"
        ]
      },
      {
        "name": "宗馥莉",
        "attributes": [
          "宗庆后之女",
          "法定代表人、董事长兼总经理",
          "[2024-08] 继承宗庆后持有的 29.4% 股权",
          "[2025-04] 收到法院立案材料"
        ]
      }
    ]
  - |
    规则：
    • 当属性直接出处于原文且符合“固有”或“最新”定义时保留。
    • “最新”必须包含日期或官方措辞（“最新”“截至××”“官方回应” 等）。
    • 输出中不保留与实体无关的细节。
